### ISSUE TITLE
Not support special data type like SqlGeometry for .net core 3.1

### ISSUE THREAD

**Issue by victor-wiki** [lkosson/reportviewercore#113]
Microsoft  has launched a prerelease version of ["Microsoft.SqlServer.Types" ](https://www.nuget.org/packages/Microsoft.SqlServer.Types/160.900.6-rc0?_src=template) that supports .net standard 2.1

**Comment by lkosson** [comment]
Not sure how I feel about that. `Microsoft.SqlServer.Types` works only on Windows because it depends on native `SqlServerSpatial160.dll`. For now I have created `sqlgeometry` branch in this repo with support for spatial types restored using `rc0` version. I haven't used spatial types at all, so as of yet it is completely untested. I can't tell if and when to merge it to master branch.

**Comment by victor-wiki** [comment]
I see. i intended to use reportiewer to render geometry data in winforms application. I have implemented it using the graphics object to draw it on picturebox.

**Comment by lkosson** [comment]
Can you checkout the `sqlgeometry` branch, compile it by yourself and check if works with your application's spatial data?

**Comment by victor-wiki** [comment]
I use the branch to run it, it can show the geometry.  Thanks!
