### ISSUE TITLE
Strong naming?

### ISSUE THREAD

**Issue by Mek7** [lkosson/reportviewercore#185]
Can you please publish a strongly named version of this library?
It would help people like me, who have strongly named code base, so only strongly named 3rd party libraries can be referenced. No impact on other people - it just broadens the usability of this library.
Thank you.

**Comment by lkosson** [comment]
.NET Core does not care about/use strong names as .NET Framework did.

**Comment by Mek7** [comment]
I have a .NET 8 project that uses the Microsoft.NET.Sdk.Web SDK.
This project is strongly named.
I get a build warning:
`Referenced assembly 'Microsoft.ReportViewer.NETCore, Version=15.1.20.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`
If .NET Core doesn't care, then why is that?

**Comment by lkosson** [comment]
As per [Microsoft docs](https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named):

> For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding.

However, in other places [[1]](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming)[[2]](https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md) they indeed recommend strong-naming publicly available libraries, specifically due to warning `CS8002`.

I'll add strong name in next release.

**Comment by Mek7** [comment]
Perfect, thank you!

**Comment by lkosson** [comment]
Signed version 15.1.21.0 is now available on nuget.
