### ISSUE TITLE
Failing to render images from RDLC for HTML

### ISSUE THREAD

**Issue by Kaderbhai** [lkosson/reportviewercore#28]
I have a RDLC file with a background image which successfully renders in a word, excel or pdf file. I'm playing with a conversion from html => pdf for possibly running on linux using dinktopdf. This works quite well apart for images (still testing on Windows btw) which don't render. 

Using HTML4.0 and HTML5 the renderer is unable to render the image in the html file, everything else does render.

Looking into the file the src looks very strange, saying that I have little experience in how rdlc files encodes these I can't be sure its strange,  only that its not rendering the image.

Any help would be greatly appreciated.

**Comment by lkosson** [comment]
Original RDLC (ReportViewer) don't support HTML export at all. This project borrowed the exporter from Reporting Services, intended to be run on a web server - that's why it tried linking img src to external hosts.

I have now modified HTML4.0 and HTML5 renderer to embed image data inside HTML instead of linking to it. Resulting HTML file is now much bigger (includes all the images as base-64 strings) but should work completely offline. See if this solves your problem. If it works properly, I'll publish NuGet package soon.

If you are trying to convert rendered HTML to PDF, consider using HTML5 exporter. It now scales images properly even with javascript disabled. HTML4.0 exporter still relies heavily on JS to set report layout.

**Comment by nshekhar1** [comment]
I have a similar issue. when I render the report to HTML5 the images are broken as below.

![brokenimage](https://user-images.githubusercontent.com/32235429/114805832-0877b080-9de7-11eb-90a7-68ebdf785359.PNG)

the image src url looks like this : http://reportserver/?&rs:Command=Get&rc:GetImage=15.0.0.0unsorted.gif

 Is there any way I can update the server url to load the image and make sorting work?

**Comment by lkosson** [comment]
Uploading the image or embedding it won't help too much in this case. Interactive sorting is a server-side operation that can't work with generated HTML. Even if images were there, clicking them would still refer to reportserver with no hope of handling or even intercepting this request.

As of now, the only workaround is to disable interactive sorting when using HTML output.

**Comment by Kaderbhai** [comment]
Apologies for not getting back sooner. 

Gave it a test finally working great thanks again.
