### ISSUE TITLE
WPF .Net 5 Support

### ISSUE THREAD

**Issue by AhmadKelany** [lkosson/reportviewercore#51]
Does it support WPF .Net 5 applications? 
I added the nuget package to the project, but couldn't figure out how to use it..

**Comment by lkosson** [comment]
I haven't tried it, but you should be able to host `Microsoft.Reporting.WinForms.ReportViewer` control from this project in your WPF .NET 5 app using `WindowsFormsHost` the same way you would host official `ReportViewer` in .NET Framework WPF application.

**Comment by AhmadKelany** [comment]
> I haven't tried it, but you should be able to host `Microsoft.Reporting.WinForms.ReportViewer` control from this project in your WPF .NET 5 app using `WindowsFormsHost` the same way you would host official `ReportViewer` in .NET Framework WPF application.

I added 
    `<UseWindowsForms>true</UseWindowsForms>`
to the project file to enable the use of WindowsFormsHost

and I added the xmlns:
       ` xmlns:report="clr-namespace:Microsoft.Reporting.NETCore;assembly=Microsoft.ReportViewer.NETCore"
`
and the code:
       ```
<WindowsFormsHost>
            <report:ReportViewer />
        </WindowsFormsHost>
```
But still it doesn't work, I get the error message:
ReportViewer does not exist in the namespace ....

**Comment by lkosson** [comment]
`ReportViewer` is in `Microsoft.ReportViewer.WinForms` namespace, not `Microsoft.ReportViewer.NETCore` you have imported.

**Comment by mohamedhamza7** [comment]
Dear @lkosson,

First, Thank you for your efforts for developing this package.

Recently there was a request to add reporting model for existing WPF .Net 5 application, and I used this package and it working fine till now, but when I try to publish a package for the application and test it but it throw exception as below when view the report
![image](https://user-images.githubusercontent.com/59682537/124377217-957a2980-dcb3-11eb-9a89-ccba34e3b0a4.png)

and after some search i found it happen because publish configured to produce a single file as below and if i uncheck this option  it report working fine.

![image](https://user-images.githubusercontent.com/59682537/124377349-2e10a980-dcb4-11eb-82fd-358ceb2bc047.png)

I found a simailer issue [here](https://stackoverflow.com/questions/57483850/error-when-embedding-report-viewer-dll-using-costura?fbclid=IwAR31eeOKBxDZy9Kzl1-dWUR2fzrkqSaE7dtjyHiJUPxarLHWUMsYxBlDFfU) and they recommend to exclude report viewer dlls from being embedded to the produce single file application

Kindly is there is a way to exclude report viewer dlls from being embedded to the produce single file application? as i tried but without any luck!
.

**Comment by lkosson** [comment]
This is the same issue as #49 - Roslyn VB compiler can't reference assembly when it's merged to a single EXE.

I don't think there is a way to prevent single DLL from being merged. Even if there is a way, that wouldn't be enough, as report compiler requires access to .NET libraries as well, so you'd have to keep those as a separate files too. At that point there would be no point of producing single EXE.

**Comment by mohamedhamza7** [comment]
Thank you so much for your kind response and explanation

**Comment by AhmadKelany** [comment]
I confirm that it is working fine with .Net 5 WPF application
