### ISSUE TITLE
Conditional Row Visibility on Grids errors on rendering

### ISSUE THREAD

**Issue by mmcgowa3** [lkosson/reportviewercore#76]
Hello,

First off, this package is a lifesaver! Great job! However, when I do use row visibility expressions to conditionally hide rows, that throws an error during rendering. Also custom field definitions don't work. I was able to work around these issues, still would be nice to have. Also, would like to have this updated for NET 6. I currently use this package on a .NET Core 3.1 web application, and it's very helpful. I tried a different package entitled AspNetCore.Reporting by WeiGe and I was not able to get that one to work. This package worked first try.

**Comment by lkosson** [comment]
Hi.

Please provide a sample report that causes said errors (ideally: RDLC to plug to `ReportViewerCore.Sample.WinForms` in this repo) and stack traces (if any) of the errors you get. Some expressions might not work due to missing support on Roslyn side (see #67). Upgrading to .NET 5 or higher should solve those.

As for .NET 6 - this package should work right away with newer runtimes. In fact, changing `<TargetFramework>netcoreapp3.1</TargetFramework>` to `<TargetFramework>net6.0-windows</TargetFramework>` in any sample project in this repo and loading it in VS2022 compiles and runs just fine.

**Comment by lkosson** [comment]
I have published new packages (15.1.16) which should resolve any conflicts due to different `Microsoft.CodeAnalysis.*` packages versions.
