### ISSUE TITLE
Missing a dll in /lib/netcoreapp3.1

### ISSUE THREAD

**Issue by moigarm** [lkosson/reportviewercore#9]
Hi, great work for doing this.
I reviewed the nuget package and found that the Microsoft.Reporting.WinForms.dll is missing, i did add a reference directly to that file in a sample project and just works.

Hope you get time to add that dll to the Nuget package, thanks in advance.

**Comment by moigarm** [comment]
![image](https://user-images.githubusercontent.com/56700986/103051358-3e550880-455c-11eb-852a-15b4cd694701.png)

**Comment by lkosson** [comment]
Hi. `ReportViewerCore.NETCore` package is intended for console and web applications - that's why it's missing Microsoft.Reporting.WinForms.dll and any references to .NET WinForms.

I have just uploaded package `ReportViewerCore.WinForms` to nuget. It includes Microsoft.Reporting.WinForms.dll and is suitable for use in desktop applications in .NET Core 3.1 and .NET 5.

**Comment by moigarm** [comment]
Many thanks, @lkosson, really helpful, Merry X-mas!
